# Generated by Django 6.0.5 on 2026-06-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("dark", "Темная"), ("light", "Светлая")],
                default="dark",
                max_length=20,
            ),
        ),
    ]
