# Generated by Django 6.0.5 on 2026-06-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("dark", "Zarya Corporate Dark"),
                    ("light", "Zarya Corporate Light"),
                ],
                default="dark",
                max_length=20,
            ),
        ),
    ]
