# Generated by Django 6.0.5 on 2026-06-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Администратор"),
                    ("MANAGER", "Финансовый директор"),
                    ("USER", "Загрузчик счетов"),
                    ("ANALYST", "Аналитик"),
                ],
                default="USER",
                max_length=20,
                verbose_name="роль",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[
                    ("dark", "Zarya Corporate Dark"),
                    ("light", "Zarya Corporate Light"),
                ],
                default="dark",
                max_length=20,
                verbose_name="тема",
            ),
        ),
    ]
