# Generated by Django 6.0.5 on 2026-07-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email_alter_user_role_alter_user_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Администратор"),
                    ("MANAGER", "Финансовый директор"),
                    ("USER", "Загрузчик документов"),
                    ("ANALYST", "Аналитик"),
                ],
                default="USER",
                max_length=20,
                verbose_name="роль",
            ),
        ),
    ]
