# Generated by Django 6.0.5 on 2026-06-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_invoice_invoice_date_invoice_invoice_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("review", "На проверке"),
                    ("approved", "Подтвержден"),
                    ("paid", "Оплачен"),
                    ("rejected", "Отклонен"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
