# Generated by Django 6.0.5 on 2026-06-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0006_invoicecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="ocr_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="OCR сумма",
            ),
        ),
    ]
