# Generated by Django 6.0.5 on 2026-06-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0007_invoice_ocr_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_verified",
            field=models.BooleanField(default=False, verbose_name="Сумма проверена"),
        ),
    ]
