# Generated by Django 6.0.5 on 2026-06-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0008_invoice_amount_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="ocr_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий OCR"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="ocr_verified",
            field=models.BooleanField(default=False, verbose_name="OCR проверен"),
        ),
    ]
