# Generated by Django 6.0.5 on 2026-06-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0009_invoice_ocr_comment_invoice_ocr_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="file_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
