# Generated by Django 6.0.5 on 2026-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0010_invoice_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="paid_at",
            field=models.DateField(blank=True, null=True, verbose_name="Дата оплаты"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_priority",
            field=models.IntegerField(default=3, verbose_name="Приоритет"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="planned_payment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Плановая дата оплаты"
            ),
        ),
    ]
