# Generated by Django 6.0.5 on 2026-06-16 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0011_invoice_paid_at_invoice_payment_priority_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "inn",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ИНН"
                    ),
                ),
                (
                    "kpp",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="КПП"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Банк"
                    ),
                ),
                (
                    "bik",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="БИК"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Расчетный счет",
                    ),
                ),
                (
                    "correspondent_account",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Корр. счет"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="invoices.counterparty",
                verbose_name="Контрагент",
            ),
        ),
    ]
