# Generated by Django 6.0.5 on 2026-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0012_counterparty_invoice_counterparty"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyRequisites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default='ОАО "Заря"',
                        max_length=255,
                        verbose_name="Наименование организации",
                    ),
                ),
                ("inn", models.CharField(max_length=20, verbose_name="ИНН")),
                (
                    "kpp",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="КПП"
                    ),
                ),
                ("bank_name", models.CharField(max_length=255, verbose_name="Банк")),
                ("bik", models.CharField(max_length=20, verbose_name="БИК")),
                (
                    "account_number",
                    models.CharField(max_length=50, verbose_name="Расчетный счет"),
                ),
                (
                    "correspondent_account",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Корреспондентский счет",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Реквизиты организации",
                "verbose_name_plural": "Реквизиты организации",
            },
        ),
    ]
