# Generated by Django 6.0.5 on 2026-06-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0013_companyrequisites"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="counterparty",
            options={
                "ordering": ["name"],
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенты",
            },
        ),
        migrations.AddField(
            model_name="counterparty",
            name="external_id_1c",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Код / ссылка 1С",
            ),
        ),
        migrations.AddField(
            model_name="counterparty",
            name="full_name",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Полное наименование",
            ),
        ),
        migrations.AddField(
            model_name="counterparty",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="counterparty",
            name="source",
            field=models.CharField(
                choices=[("1c", "1С"), ("manual", "Вручную"), ("ocr", "OCR")],
                default="ocr",
                max_length=20,
                verbose_name="Источник",
            ),
        ),
        migrations.AddField(
            model_name="counterparty",
            name="sync_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий синхронизации"
            ),
        ),
        migrations.AddField(
            model_name="counterparty",
            name="synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата синхронизации"
            ),
        ),
        migrations.AddField(
            model_name="counterparty",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="counterparty_match_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий поиска контрагента"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="counterparty_match_status",
            field=models.CharField(
                choices=[
                    ("not_processed", "Не проверялся"),
                    ("found", "Найден"),
                    ("not_found", "Не найден в 1С"),
                    ("ambiguous", "Найдено несколько вариантов"),
                ],
                default="not_processed",
                max_length=30,
                verbose_name="Статус поиска контрагента",
            ),
        ),
        migrations.AlterField(
            model_name="counterparty",
            name="inn",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, verbose_name="ИНН"
            ),
        ),
        migrations.AlterField(
            model_name="counterparty",
            name="kpp",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, verbose_name="КПП"
            ),
        ),
    ]
