# Generated by Django 6.0.5 on 2026-06-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0014_alter_counterparty_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="file_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="Хэш файла",
            ),
        ),
    ]
