# Generated by Django 6.0.5 on 2026-06-17 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0015_alter_invoice_file_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceUploadBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Токен загрузки",
                    ),
                ),
                (
                    "total_files",
                    models.PositiveIntegerField(default=0, verbose_name="Всего файлов"),
                ),
                (
                    "uploaded_count",
                    models.PositiveIntegerField(default=0, verbose_name="Новых счетов"),
                ),
                (
                    "duplicate_count",
                    models.PositiveIntegerField(default=0, verbose_name="Дубликатов"),
                ),
                (
                    "skipped_count",
                    models.PositiveIntegerField(default=0, verbose_name="Пропущено"),
                ),
                (
                    "duplicate_files",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Файлы-дубликаты"
                    ),
                ),
                (
                    "skipped_files",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Пропущенные файлы"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Загружено"),
                            ("partial", "Частично загружено"),
                            ("empty", "Новых файлов нет"),
                        ],
                        db_index=True,
                        default="empty",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_upload_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пакет загрузки счетов",
                "verbose_name_plural": "Пакеты загрузки счетов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="upload_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="invoices.invoiceuploadbatch",
                verbose_name="Пакет загрузки",
            ),
        ),
    ]
