# Generated by Django 6.0.5 on 2026-06-18 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0016_invoiceuploadbatch_invoice_upload_batch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OCRJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "Выполняется"),
                            ("done", "Готово"),
                            ("error", "Ошибка"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Вручную"),
                            ("single", "Карточка счета"),
                            ("bulk", "Массовая постановка"),
                            ("upload", "Загрузка файла"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Попыток"),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Сообщение"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="Ошибка"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Начато"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершено"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_jobs",
                        to="invoices.invoice",
                        verbose_name="Счет",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocr_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR задача",
                "verbose_name_plural": "OCR задачи",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="invoices_oc_status_7db0de_idx",
                    )
                ],
            },
        ),
    ]
