# Generated by Django 6.0.5 on 2026-06-22 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0017_ocrjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название реестра"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("checked", "Проверен"),
                            ("exported", "Выгружен"),
                            ("partially_paid", "Частично оплачен"),
                            ("paid", "Оплачен"),
                            ("cancelled", "Отменён"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата проверки"
                    ),
                ),
                (
                    "exported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата выгрузки"
                    ),
                ),
                (
                    "items_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество счетов"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Сумма реестра",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_payment_registries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверил",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payment_registries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "exported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exported_payment_registries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Выгрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реестр оплаты",
                "verbose_name_plural": "Реестры оплаты",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PaymentRegistryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Сумма"
                    ),
                ),
                (
                    "planned_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Плановая дата оплаты"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("added", "Добавлен"),
                            ("exported", "Выгружен"),
                            ("paid", "Оплачен"),
                            ("cancelled", "Отменён"),
                        ],
                        db_index=True,
                        default="added",
                        max_length=32,
                        verbose_name="Статус строки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "exported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата выгрузки"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_registry_items",
                        to="invoices.invoice",
                        verbose_name="Счёт",
                    ),
                ),
                (
                    "registry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.paymentregistry",
                        verbose_name="Реестр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка реестра оплаты",
                "verbose_name_plural": "Строки реестра оплаты",
                "ordering": ("planned_payment_date", "invoice_id"),
            },
        ),
        migrations.AddIndex(
            model_name="paymentregistry",
            index=models.Index(
                fields=["status", "created_at"], name="invoices_pa_status_3fc2d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentregistry",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="invoices_pa_created_5a827d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentregistryitem",
            index=models.Index(
                fields=["registry", "status"], name="invoices_pa_registr_499930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentregistryitem",
            index=models.Index(
                fields=["invoice", "status"], name="invoices_pa_invoice_e3c663_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentregistryitem",
            index=models.Index(
                fields=["planned_payment_date"], name="invoices_pa_planned_1108d5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentregistryitem",
            constraint=models.UniqueConstraint(
                fields=("registry", "invoice"),
                name="unique_invoice_in_payment_registry",
            ),
        ),
    ]
