# Generated by Django 6.0.5 on 2026-06-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0018_paymentregistry_paymentregistryitem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentregistry",
            options={
                "ordering": ("-created_at",),
                "permissions": (
                    ("can_manage_payment_registry", "Может управлять реестрами оплаты"),
                    ("can_check_payment_registry", "Может проверять реестры оплаты"),
                    ("can_export_payment_registry", "Может выгружать реестры оплаты"),
                    (
                        "can_mark_payment_registry_paid",
                        "Может отмечать реестры оплаты оплаченными",
                    ),
                    ("can_cancel_payment_registry", "Может отменять реестры оплаты"),
                ),
                "verbose_name": "Реестр оплаты",
                "verbose_name_plural": "Реестры оплаты",
            },
        ),
    ]
