# Generated by Django 6.0.5 on 2026-06-23 07:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0019_alter_paymentregistry_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("posted", "Проведён"), ("cancelled", "Отменён")],
                        default="posted",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Ручная оплата"),
                            ("registry", "Реестр оплаты"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма оплаты"
                    ),
                ),
                (
                    "paid_at",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата оплаты",
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Номер платёжного документа",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoice_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто внёс",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoices.invoice",
                        verbose_name="Счёт",
                    ),
                ),
                (
                    "registry_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="invoices.paymentregistryitem",
                        verbose_name="Строка реестра оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж по счёту",
                "verbose_name_plural": "Платежи по счетам",
                "ordering": ("-paid_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["invoice", "status"],
                        name="invoices_in_invoice_16ad84_idx",
                    ),
                    models.Index(
                        fields=["paid_at", "status"],
                        name="invoices_in_paid_at_ec1976_idx",
                    ),
                    models.Index(
                        fields=["registry_item", "status"],
                        name="invoices_in_registr_242351_idx",
                    ),
                ],
            },
        ),
    ]
