# Generated by Django 6.0.5 on 2026-07-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0020_invoicepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="document_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Дата документа"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="document_type",
            field=models.CharField(
                choices=[("invoice", "Счёт"), ("upd", "УПД")],
                db_index=True,
                default="invoice",
                max_length=20,
                verbose_name="Тип документа",
            ),
        ),
    ]
