# Generated by Django 6.0.5 on 2026-07-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0021_invoice_document_date_invoice_document_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто удалил",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Удалён"
            ),
        ),
    ]
