# Generated by Django 6.0.5 on 2026-07-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0022_invoice_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentregistry",
            name="paid_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Дата фактической оплаты",
            ),
        ),
    ]
