# Generated by Django 6.0.5 on 2026-07-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0024_add_waybill_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("in_work", "В работе"),
                    ("on_approval", "На согласовании"),
                    ("approved", "Утверждён"),
                    ("paid", "Оплачен"),
                    ("rejected", "Отклонён"),
                ],
                default="new",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
