# Generated by Django 6.0.5 on 2026-07-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0025_invoice_status_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("invoice", "Счёт"),
                    ("upd", "УПД"),
                    ("waybill", "Товарная накладная"),
                    ("payment_document", "Платёжный документ"),
                    ("unknown", "Неизвестный тип"),
                ],
                db_index=True,
                default="invoice",
                max_length=20,
                verbose_name="Тип документа",
            ),
        ),
    ]
