# Generated by Django 6.0.5 on 2026-07-14 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0026_payment_document_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponsiblePerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(db_index=True, max_length=255, verbose_name="ФИО"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответственный",
                "verbose_name_plural": "Ответственные",
                "ordering": ("full_name", "id"),
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="invoices.responsibleperson",
                verbose_name="Ответственный",
            ),
        ),
    ]
