# Generated by Django 6.0.5 on 2026-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OCRJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает"),
                            ("PROCESSING", "Обработка"),
                            ("DONE", "Готово"),
                            ("ERROR", "Ошибка"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("result_text", models.TextField(blank=True, null=True)),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("error_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
