# Generated by Django 6.0.5 on 2026-06-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrjob",
            name="invoice_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
